version: 0.2



phases:

  install:

    runtime-versions:

      python: 3.7

    commands:

      - tf_version=$TERRAFORM_VERSION

      - wget https://releases.hashicorp.com/terraform/"$TERRAFORM_VERSION"/terraform_"$TERRAFORM_VERSION"_linux_amd64.zip

      - unzip terraform_"$TERRAFORM_VERSION"_linux_amd64.zip

      - mv terraform /usr/local/bin/

      - curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash


      - curl -Lo ./terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/v0.16.0/terraform-docs-v0.16.0-$(uname)-amd64.tar.gz
      - tar -xzf terraform-docs.tar.gz
      - chmod +x terraform-docs
      - mv terraform-docs /usr/local/terraform-docs

  build:

    commands:

      - terraform --version

      - terraform init -input=false

      - tflint --init

      - terraform validate

      - terraform fmt .